[package]
name = "leveldb_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "1.3"
db-key = "0.0.5"
leveldb = "0.8"
serde   = { version = "1.0", features = ["derive"] }
tempdir = "0.3"
